name: deploy-model-training-pipeline

on: 
  workflow_dispatch:
permissions:
  id-token: write
  contents: read
jobs:
  get-config:
      uses: Azure/mlops-templates/.github/workflows/read-yaml.yml@main
      with:
        file_name: config-infra-prod.yml
  register-environment:
      needs: get-config
      uses: Azure/mlops-templates/.github/workflows/register-environment.yml@Dec2025patch
      with:
        resource_group: ${{ needs.get-config.outputs.resource_group }}
        workspace_name: ${{ needs.get-config.outputs.aml_workspace }}     
        environment_file:  mlops/azureml/train/train-env.yml
        conda_file: data-science/environment/train-conda.yml
      secrets:
          AZURE_CLIENT_ID: ${{ secrets.AZURE_CLIENT_ID }}
          AZURE_TENANT_ID: ${{ secrets.AZURE_TENANT_ID }}
          AZURE_SUBSCRIPTION_ID: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
          
  register-dataset:
    needs: get-config
    uses: Azure/mlops-templates/.github/workflows/register-dataset.yml@Dec2025patch
    with:
      resource_group: ${{ needs.get-config.outputs.resource_group }}
      workspace_name: ${{ needs.get-config.outputs.aml_workspace }}
      name: taxi-data
      data_file: mlops/azureml/train/data.yml
    secrets:
      AZURE_CLIENT_ID: ${{ secrets.AZURE_CLIENT_ID }}
      AZURE_TENANT_ID: ${{ secrets.AZURE_TENANT_ID }}
      AZURE_SUBSCRIPTION_ID: ${{ secrets.AZURE_SUBSCRIPTION_ID }}

  create-compute:
      needs: [get-config,register-environment,register-dataset]
      uses: Azure/mlops-templates/.github/workflows/create-compute.yml@Dec2025patch
      with:
        cluster_name: cpu-cluster
        size: Standard_DS3_v2
        min_instances: 0
        max_instances: 4
        cluster_tier: low_priority
        resource_group: ${{ needs.get-config.outputs.resource_group }}
        workspace_name: ${{ needs.get-config.outputs.aml_workspace }}     
      secrets:
            AZURE_CLIENT_ID: ${{ secrets.AZURE_CLIENT_ID }}
            AZURE_TENANT_ID: ${{ secrets.AZURE_TENANT_ID }}
            AZURE_SUBSCRIPTION_ID: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
      
  run-pipeline:
      needs: [get-config,register-environment,create-compute,register-dataset]
      uses: Azure/mlops-templates/.github/workflows/run-pipeline.yml@Dec2025patch
      with:
        resource_group: ${{ needs.get-config.outputs.resource_group }}
        workspace_name: ${{ needs.get-config.outputs.aml_workspace }}     
        parameters-file:  mlops/azureml/train/pipeline.yml
        job-name: test
      secrets:
            AZURE_CLIENT_ID: ${{ secrets.AZURE_CLIENT_ID }}
            AZURE_TENANT_ID: ${{ secrets.AZURE_TENANT_ID }}
            AZURE_SUBSCRIPTION_ID: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
