name: deploy-batch-endpoint-pipeline

on: 
  workflow_dispatch:
jobs:
  get-config:
      uses: Azure/mlops-templates/.github/workflows/read-yaml.yml@main
      with:
        file_name: config-infra-prod.yml
  create-compute:
      needs: get-config
      uses: Azure/mlops-templates/.github/workflows/create-compute.yml@Dec2025patch
      with:
        cluster_name: batch-cluster
        size: STANDARD_DS3_V2
        min_instances: 0
        max_instances: 1
        resource_group: ${{ needs.get-config.outputs.resource_group }}
        workspace_name: ${{ needs.get-config.outputs.aml_workspace }}     
      secrets:
          AZURE_CLIENT_ID: ${{ secrets.AZURE_CLIENT_ID }}
          AZURE_TENANT_ID: ${{ secrets.AZURE_TENANT_ID }}
          AZURE_SUBSCRIPTION_ID: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
  create-endpoint:
      needs: [get-config,create-compute]
      uses: Azure/mlops-templates/.github/workflows/create-endpoint.yml@Dec2025patch
      with:
        resource_group: ${{ needs.get-config.outputs.resource_group }}
        workspace_name: ${{ needs.get-config.outputs.aml_workspace }} 
        endpoint_file: mlops/azureml/deploy/batch/batch-endpoint.yml
        endpoint_name:  ${{ format('taxi-gha-{0}', needs.get-config.outputs.bep) }} 
        endpoint_type: batch
      secrets:
          AZURE_CLIENT_ID: ${{ secrets.AZURE_CLIENT_ID }}
          AZURE_TENANT_ID: ${{ secrets.AZURE_TENANT_ID }}
          AZURE_SUBSCRIPTION_ID: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
  create-deployment:
      uses: Azure/mlops-templates/.github/workflows/create-deployment.yml@Dec2025patch
      needs: [get-config,create-endpoint]
      with:
        resource_group: ${{ needs.get-config.outputs.resource_group }}
        workspace_name: ${{ needs.get-config.outputs.aml_workspace }} 
        endpoint_file: mlops/azureml/deploy/batch/batch-deployment.yml
        endpoint_name: ${{ format('taxi-gha-{0}', needs.get-config.outputs.bep) }} 
        endpoint_type: batch
        deployment_name: eptestdeploy
      secrets:
          AZURE_CLIENT_ID: ${{ secrets.AZURE_CLIENT_ID }}
          AZURE_TENANT_ID: ${{ secrets.AZURE_TENANT_ID }}
          AZURE_SUBSCRIPTION_ID: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
